/* Generated by Header_Generator V1.0 */

/*
* Project Name ->	Switchy
* Version      ->	V1.0
* Author       ->	Hm	
* Build Date   ->	26.04.2017
* Description  ->	Zeitschaltuhr
*
*
*
*/

#ifndef HARD_DEF_H
#define HARD_DEF_H


#define LCD_DDR			DDRD
#define LCD_PORT		PORTD
enum lcd_ctrl
{
	READ_WRITE		= 1<<7,
	ENABLE			= 1<<6,
	CONTRAST		= 1<<5,
	ILLUMINATION	= 1<<4,
	DB4				= 1<<3,
	DB5				= 1<<2,
	DB6				= 1<<1,	
	DB7				= 1<<0,
};

#define LCD_RS_DDR		DDRC
#define LCD_RS_PORT		PORTC
enum lcd_rs_ctrl
{
	RS				= 1<<2,	
};

#define ENCODER_DDR		DDRC
#define ENCODER_PORT	PINC
enum encoder_ctrl
{
	PHASE_B			= 1<<5,
	PHASE_A			= 1<<4,
	ENTER			= 1<<3,	
};

#define TRIAC_DDR		DDRB
#define TRIAC_PORT		PORTB
enum triac_ctrl
{
	TRIAC3			= 1<<4,
	TRIAC2			= 1<<3,
	TRIAC1			= 1<<2,	
};


#define LED_DDR			DDRA
#define LED_PORT		PORTA
enum led_ctrl
{
	STATE_LED4		= 1<<3,
	STATE_LED3		= 1<<2,
	STATE_LED2		= 1<<1,
	STATE_LED1		= 1<<0,	
};


#endif